/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package misc.kazova;

import java.awt.Graphics;
import java.awt.image.BufferedImage;
import jazari.image_processing.ImageProcess;

/**
 *
 * @author cezerilab
 */
public class Canvas extends javax.swing.JPanel {
    BufferedImage img;

    /**
     * Creates new form Canvas
     */
    public Canvas() {
        initComponents();
        img=ImageProcess.imread("images/rice.png");
        //img=ImageProcess.imread("images/screenshot.jpg");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void paint(Graphics gr) {
        //gr.drawImage(img, 0,0, this);
        gr.drawImage(img,0,0,(int)(0.8*img.getWidth()),(int)(0.8*img.getHeight()),null);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
