/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jazari.gui;

import com.formdev.flatlaf.FlatDarculaLaf;
import jazari.image_processing.ImageProcess;
import jazari.matrix.CMatrix;
import jazari.factory.FactoryUtils;
import java.io.File;
import jazari.types.TFigureAttribute;

/**
 *
 * @author BAP1
 */
public class FrameBar extends javax.swing.JFrame {

    private CMatrix cm;
    private String[] labels;
    private boolean isValueVisible;


//    public FrameBar(CMatrix cm) {
//        super(cm.name+"|Bar");
//        cm.name+="|Bar";
//        this.cm =cm.clone();
//        initComponents();
//    }
    
    public FrameBar(CMatrix cm, String[] labels) {
        super(cm.name+"|Bar");
        FlatDarculaLaf.setup();
        cm.name+="|Bar";
        this.cm =cm.clone();
        this.labels=labels;
        initComponents();
    }
    
    public void setLabels(String ... labels){
        this.labels=labels;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_plot = new jazari.gui.PanelBar(this,cm,labels,isValueVisible);
        jPanel1 = new javax.swing.JPanel();
        btn_dataGrid = new javax.swing.JButton();
        btn_scatter = new javax.swing.JButton();
        btn_save = new javax.swing.JButton();
        txt_dpi = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btn_refresh = new javax.swing.JButton();
        chk_legend = new javax.swing.JCheckBox();
        chk_dark_mode = new javax.swing.JCheckBox();
        chk_gridy = new javax.swing.JCheckBox();
        chk_gridx = new javax.swing.JCheckBox();
        combo_line_type = new javax.swing.JComboBox<>();
        chk_transpose = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panel_plot.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout panel_plotLayout = new javax.swing.GroupLayout(panel_plot);
        panel_plot.setLayout(panel_plotLayout);
        panel_plotLayout.setHorizontalGroup(
            panel_plotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 888, Short.MAX_VALUE)
        );
        panel_plotLayout.setVerticalGroup(
            panel_plotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 505, Short.MAX_VALUE)
        );

        btn_dataGrid.setText("Data Grid");
        btn_dataGrid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dataGridActionPerformed(evt);
            }
        });

        btn_scatter.setText("scatter");
        btn_scatter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_scatterActionPerformed(evt);
            }
        });

        btn_save.setText("Save");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });

        txt_dpi.setText("300");

        jLabel3.setText("dpi");

        btn_refresh.setText("refresh");
        btn_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_refreshActionPerformed(evt);
            }
        });

        chk_legend.setSelected(true);
        chk_legend.setText("legend");
        chk_legend.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chk_legendItemStateChanged(evt);
            }
        });
        chk_legend.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                chk_legendPropertyChange(evt);
            }
        });

        chk_dark_mode.setSelected(true);
        chk_dark_mode.setText("dark mode");
        chk_dark_mode.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chk_dark_modeİtemStateChanged(evt);
            }
        });

        chk_gridy.setSelected(true);
        chk_gridy.setText("gridy");
        chk_gridy.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chk_gridyİtemStateChanged(evt);
            }
        });

        chk_gridx.setSelected(true);
        chk_gridx.setText("gridx");
        chk_gridx.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chk_gridxİtemStateChanged(evt);
            }
        });

        combo_line_type.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        combo_line_type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", ".", "*", "o" }));
        combo_line_type.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combo_line_typeİtemStateChanged(evt);
            }
        });

        chk_transpose.setText("transpose");
        chk_transpose.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chk_transposeİtemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btn_dataGrid)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_scatter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_save, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_dpi, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_refresh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addComponent(chk_transpose, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(combo_line_type, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chk_gridx, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chk_gridy)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chk_dark_mode)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chk_legend)
                .addGap(14, 14, 14))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_dataGrid)
                    .addComponent(btn_scatter)
                    .addComponent(btn_save)
                    .addComponent(txt_dpi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(btn_refresh)
                    .addComponent(chk_legend)
                    .addComponent(chk_dark_mode)
                    .addComponent(chk_gridy)
                    .addComponent(chk_gridx)
                    .addComponent(combo_line_type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chk_transpose))
                .addGap(0, 9, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_plot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_plot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_dataGridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dataGridActionPerformed
        CMatrix cm = getBarPanel().getMatrix();
        new FrameDataGrid(cm).setVisible(true);
    }//GEN-LAST:event_btn_dataGridActionPerformed

    private void btn_scatterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_scatterActionPerformed
        if (getBarPanel().getMatrix().getColumnNumber()<2) {
            System.err.println("number of columns should be at least 2");
            return;
        }
        TFigureAttribute attr = new TFigureAttribute();
        attr.figureCaption = this.getTitle();
        getBarPanel().getMatrix().scatter(attr);
    }//GEN-LAST:event_btn_scatterActionPerformed

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        savePanel();
    }//GEN-LAST:event_btn_saveActionPerformed

    private void btn_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_refreshActionPerformed
        getBarPanel().setMatrix(this.cm);
    }//GEN-LAST:event_btn_refreshActionPerformed

    private void chk_legendItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chk_legendItemStateChanged
        getBarPanel().setLegend(chk_legend.isSelected());
    }//GEN-LAST:event_chk_legendItemStateChanged

    private void chk_legendPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_chk_legendPropertyChange

    }//GEN-LAST:event_chk_legendPropertyChange

    private void chk_dark_modeİtemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chk_dark_modeİtemStateChanged
        getBarPanel().setDarkMode(chk_dark_mode.isSelected());
    }//GEN-LAST:event_chk_dark_modeİtemStateChanged

    private void chk_gridyİtemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chk_gridyİtemStateChanged
        getBarPanel().setGridy(chk_gridy.isSelected());
    }//GEN-LAST:event_chk_gridyİtemStateChanged

    private void chk_gridxİtemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chk_gridxİtemStateChanged
        getBarPanel().setGridx(chk_gridx.isSelected());
    }//GEN-LAST:event_chk_gridxİtemStateChanged

    private void combo_line_typeİtemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combo_line_typeİtemStateChanged
        getBarPanel().setPointType(combo_line_type.getSelectedItem().toString());
    }//GEN-LAST:event_combo_line_typeİtemStateChanged

    private void chk_transposeİtemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chk_transposeİtemStateChanged
        getBarPanel().setTranspose(chk_transpose.isSelected());
    }//GEN-LAST:event_chk_transposeİtemStateChanged

    public PanelBar getBarPanel() {
        return (PanelBar) panel_plot;
    }
    
    public void setBarData(CMatrix cmx){
        this.cm = cmx.getHistogram();
        getBarPanel().setMatrix(cm);
    }

    public void setBarData(CMatrix cmx, String[] labels){
        this.cm = cmx.getHistogram();
        getBarPanel().setMatrix(cm, labels);
    }

    /**
     * param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_dataGrid;
    private javax.swing.JButton btn_refresh;
    private javax.swing.JButton btn_save;
    private javax.swing.JButton btn_scatter;
    private javax.swing.JCheckBox chk_dark_mode;
    private javax.swing.JCheckBox chk_gridx;
    private javax.swing.JCheckBox chk_gridy;
    private javax.swing.JCheckBox chk_legend;
    private javax.swing.JCheckBox chk_transpose;
    private javax.swing.JComboBox<String> combo_line_type;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panel_plot;
    private javax.swing.JTextField txt_dpi;
    // End of variables declaration//GEN-END:variables

    private void savePanel() {
        PanelBar cp = getBarPanel();
        int dpi = Integer.parseInt(txt_dpi.getText());
        double scale = dpi / 96.0;
        cp.setSize((int) (cp.getWidth() * scale), (int) (cp.getHeight() * scale));
        File file = FactoryUtils.getFileFromChooserSave();
        if (file != null) {
            ImageProcess.saveGridImage(ImageProcess.getBufferedImage(getBarPanel()), file.getAbsolutePath());
        } else {
            FactoryUtils.showMessage("kaydedilemedi CPlotFrame.savePanel()");
        }
        cp.setSize((int) (cp.getWidth() / scale), (int) (cp.getHeight() / scale));
    }

    public void setValuVisible(boolean valueVisible) {
        this.isValueVisible=valueVisible;
        getBarPanel().setValueVisible(isValueVisible);
    }
    
//    public static void main(String[] args) {
//        FlatDarculaLaf.setup();
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                FrameBar jazo = new FrameBar(null,null);
//                jazo.setVisible(true);
//            }
//        });
//    }


}
